In [10]:
pwd

'/Users/baijingyuan/jupyterPj/pytorch_practice'

import torch

In [13]:
torch.empty(3,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
x = torch.tensor([5.5, 3])

In [17]:
print(x)

tensor([5.5000, 3.0000])


In [22]:
x = torch.rand(5,3)

In [24]:
print(x)

tensor([[0.3022, 0.9977, 0.3151],
        [0.3147, 0.3222, 0.7463],
        [0.1571, 0.3295, 0.3977],
        [0.6116, 0.7345, 0.9638],
        [0.1245, 0.7521, 0.3267]])


In [61]:
result = torch.empty(5, 3)
x = torch.rand(5, 3)
y = torch.rand(5, 3)
result = torch.add(x, y)
print(x, y, result)

tensor([[0.7988, 0.4484, 0.4187],
        [0.4488, 0.2201, 0.7110],
        [0.1796, 0.9812, 0.5387],
        [0.5059, 0.1817, 0.4603],
        [0.5799, 0.3885, 0.6683]]) tensor([[0.9356, 0.7896, 0.9591],
        [0.5162, 0.5644, 0.1231],
        [0.3896, 0.6357, 0.9558],
        [0.6159, 0.1719, 0.3662],
        [0.7664, 0.5161, 0.4988]]) tensor([[1.7344, 1.2380, 1.3778],
        [0.9650, 0.7845, 0.8340],
        [0.5691, 1.6169, 1.4945],
        [1.1217, 0.3536, 0.8265],
        [1.3463, 0.9046, 1.1671]])


In [62]:
result.size()

torch.Size([5, 3])

In [63]:
y.size()

torch.Size([5, 3])

In [75]:
torch.Tensor([5, 3])
torch.tensor([5, 3])

tensor([5, 3])

In [81]:
y = torch.randn(5, 3) 
x = torch.rand(5, 3)

In [83]:
print(x)

tensor([[0.8220, 0.0360, 0.8679],
        [0.5416, 0.7822, 0.0012],
        [0.0966, 0.8848, 0.9145],
        [0.9756, 0.1376, 0.3397],
        [0.3591, 0.2048, 0.8002]])


In [85]:
print(y)

tensor([[-0.5581, -0.1057,  0.4288],
        [ 0.9190,  1.6343,  0.0696],
        [ 1.2717,  0.9356, -1.0167],
        [-0.4650,  0.4329,  0.7812],
        [ 0.9244, -0.9421, -0.0802]])


In [6]:
import torch
x = torch.FloatTensor([5, 3])
y = torch.IntTensor([5.0, 3.0])

In [9]:
print(x)

tensor([5., 3.])


In [11]:
print(y)

tensor([5, 3], dtype=torch.int32)


In [13]:
a = torch.randn(5,3)

In [15]:
print(a)

tensor([[ 0.9500, -1.4548, -1.9308],
        [ 0.0068, -0.6253, -0.2284],
        [ 0.8488, -0.3014, -1.3392],
        [-1.1099,  0.3267,  1.3600],
        [-0.5708,  2.1047,  0.5551]])


randn   均值为0, 方差为1, float

In [18]:
import torch
x = torch.arange(0, 12).reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [20]:
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [24]:
x = torch.empty(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
a = torch.randn(2, 3)
a

tensor([[-0.0570, -0.6950,  0.7398],
        [-0.2683,  0.0319, -0.6639]])

In [30]:
b = torch.abs(a)
b

tensor([[0.0570, 0.6950, 0.7398],
        [0.2683, 0.0319, 0.6639]])

In [34]:
x = torch.rand(2, 3)
x

tensor([[0.4057, 0.0684, 0.0440],
        [0.0549, 0.5517, 0.3807]])

In [36]:
y = torch.rand(2, 3)
y

tensor([[0.9987, 0.7820, 0.4576],
        [0.3514, 0.1293, 0.0601]])

In [38]:
z = torch.add(x, y)
z

tensor([[1.4044, 0.8504, 0.5017],
        [0.4062, 0.6810, 0.4408]])

In [40]:
z = torch.add(x, 10)
z

tensor([[10.4057, 10.0684, 10.0440],
        [10.0549, 10.5517, 10.3807]])

In [42]:
a = torch.tensor([1, 2, 3, 4, 5, 6]).reshape(2, 3)
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [44]:
b = torch.clamp(a, 3, 3)

In [46]:
b

tensor([[3, 3, 3],
        [3, 3, 3]])

In [48]:
b = torch.clamp(a, 3, 4)

In [50]:
b

tensor([[3, 3, 3],
        [4, 4, 4]])

In [52]:
c = torch.div(a, b)
c

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.2500, 1.5000]])

In [2]:
import torch

In [4]:
a = torch.tensor([2, 3, 4])
a

tensor([2, 3, 4])

In [8]:
a = torch.pow(a, 2)
a

tensor([ 16,  81, 256])

In [10]:
a = torch.tensor([2, 3, 4])
a

tensor([2, 3, 4])

In [12]:
b = torch.pow(a, 2)

In [14]:
b

tensor([ 4,  9, 16])

In [18]:
a = torch.tensor([[1, 2, 3],[2, 3, 4]])
a

tensor([[1, 2, 3],
        [2, 3, 4]])

In [20]:
b = torch.tensor([[2, 3, 4],[1, 1, 1]])
b

tensor([[2, 3, 4],
        [1, 1, 1]])

In [22]:
c = torch.mm(a, b.T)

In [24]:
c

tensor([[20,  6],
        [29,  9]])

In [6]:
import torch
a = torch.randn(2, 3)
a

tensor([[-0.0929, -0.0762, -1.5224],
        [ 1.0897,  0.0570,  1.7094]])

In [8]:
b = torch.randn(3)
b

tensor([ 1.6427, -1.1543, -1.3970])

In [10]:
c = torch.mv(a, b)
c

tensor([ 2.0622, -0.6639])

In [6]:
#这里用torch.nn实现一个MLP
from torch import nn

class MLP(nn.Module):
    def __init__(self, in_dim, hid_dim1, hid_dim2, out_dim):
        super(MLP, self).__init__()
        self.layer = nn.Sequential(
          nn.Linear(in_dim, hid_dim1),
          nn.ReLU(),
          nn.Linear(hid_dim1, hid_dim2),
          nn.ReLU(),
          nn.Linear(hid_dim2, out_dim),
          nn.ReLU()
       )
    def forward(self, x):
        x = self.layer(x)
        return x

# 简易神经网络

In [ ]:
import torch
batch_n = 100#一个批次输入数据的数量
hidden_layer = 100
input_data = 1000#每个数据的特征为1000
output_data = 10

x = torch.randn(batch_n,input_data)
y = torch.randn(batch_n,output_data)


w1 = torch.randn(input_data,hidden_layer)
w2 = torch.randn(hidden_layer,output_data)

epoch_n = 20
lr = 1e-6


for epoch in range(epoch_n):
    h1=x.mm(w1)#(100,1000)*(1000,100)-->100*100
    print(h1.shape)
    h1=h1.clamp(min=0)
    y_pred = h1.mm(w2)
    
    loss = (y_pred-y).pow(2).sum()
    print("epoch:{},loss:{:.4f}".format(epoch,loss))
    
    grad_y_pred = 2*(y_pred-y)
    grad_w2 = h1.t().mm(grad_y_pred)
    
    grad_h = grad_y_pred.clone()
    grad_h = grad_h.mm(w2.t())
    grad_h.clamp_(min=0)#将小于0的值全部赋值为0，相当于sigmoid
    grad_w1 = x.t().mm(grad_h)
    
    w1 = w1 -lr*grad_w1
    w2 = w2 -lr*grad_w2


# 输入层 (X，100*1000维特征)
    |
    | 线性变换 (权重 W1 1000*100层)
    v
# 隐藏层线性输出 (H1_linear 100*100)
    |
    | 激活函数 (ReLU min=0)
    v
# 隐藏层激活输出 (H1  100*100)
    |
    | 线性变换 (权重 W2 100*10)
    v
# 输出层预测值 (Y_pred 100*10)
    |
    | 损失函数 (如均方误差  sigma(y_pred - y))
    v
# 损失值 (Loss)

#
#
#


# 损失值 (Loss)
    ^
    | 计算损失对预测输出 Y_pred 的梯度
    |
# 输出层预测值 (Y_pred)
    ^
    | 计算损失对 W2 和 H1 的梯度
    |
# 隐藏层激活输出 (H1)
    ^
    | 计算激活函数 (ReLU) 的梯度
    |
# 隐藏层线性输出 (H1_linear)
    ^
    | 计算损失对 W1 的梯度
    |
# 输入层 (X)


In [2]:
import torch
a = torch.randn(2, 3)
a

tensor([[-0.4184,  0.3846, -0.3964],
        [-0.5934,  0.5525,  0.4002]])

In [4]:
b = torch.randn(2, 3)
b

tensor([[ 0.3364, -0.6805,  0.5913],
        [ 0.0210,  0.6166, -0.6118]])

In [6]:
c = torch.div(a, b)
c

tensor([[ -1.2436,  -0.5651,  -0.6704],
        [-28.2244,   0.8962,  -0.6542]])

# 完整神经网络

In [2]:
import torch
from torch.autograd import Variable
batch_n = 100#一个批次输入数据的数量
hidden_layer = 100
input_data = 1000#每个数据的特征为1000
output_data = 10

x = Variable(torch.randn(batch_n,input_data),requires_grad=False)
y = Variable(torch.randn(batch_n,output_data),requires_grad=False)
#用Variable对Tensor数据类型变量进行封装的操作。requires_grad如果是False，表示该变量在进行自动梯度计算的过程中不会保留梯度值。
w1 = Variable(torch.randn(input_data,hidden_layer),requires_grad=True)
w2 = Variable(torch.randn(hidden_layer,output_data),requires_grad=True)

#学习率和迭代次数
epoch_n=50
lr=1e-6

for epoch in range(epoch_n):
    h1=x.mm(w1)#(100,1000)*(1000,100)-->100*100
    print(h1.shape)
    h1=h1.clamp(min=0)
    y_pred = h1.mm(w2)
    #y_pred = x.mm(w1).clamp(min=0).mm(w2)
    loss = (y_pred-y).pow(2).sum()
    print("epoch:{},loss:{:.4f}".format(epoch,loss.data))
    
#     grad_y_pred = 2*(y_pred-y)
#     grad_w2 = h1.t().mm(grad_y_pred)
    loss.backward()#后向传播
#     grad_h = grad_y_pred.clone()
#     grad_h = grad_h.mm(w2.t())
#     grad_h.clamp_(min=0)#将小于0的值全部赋值为0，相当于sigmoid
#     grad_w1 = x.t().mm(grad_h)
    w1.data -= lr*w1.grad.data
    w2.data -= lr*w2.grad.data

    w1.grad.data.zero_()
    w2.grad.data.zero_()
    
#     w1 = w1 -lr*grad_w1
#     w2 = w2 -lr*grad_w2


torch.Size([100, 100])
epoch:0,loss:82381360.0000
torch.Size([100, 100])
epoch:1,loss:245776192.0000
torch.Size([100, 100])
epoch:2,loss:654988416.0000
torch.Size([100, 100])
epoch:3,loss:249465312.0000
torch.Size([100, 100])
epoch:4,loss:14112704.0000
torch.Size([100, 100])
epoch:5,loss:8451636.0000
torch.Size([100, 100])
epoch:6,loss:5683316.5000
torch.Size([100, 100])
epoch:7,loss:4101432.2500
torch.Size([100, 100])
epoch:8,loss:3117549.5000
torch.Size([100, 100])
epoch:9,loss:2469978.0000
torch.Size([100, 100])
epoch:10,loss:2024292.8750
torch.Size([100, 100])
epoch:11,loss:1706489.8750
torch.Size([100, 100])
epoch:12,loss:1472251.6250
torch.Size([100, 100])
epoch:13,loss:1294332.5000
torch.Size([100, 100])
epoch:14,loss:1155113.2500
torch.Size([100, 100])
epoch:15,loss:1043136.7500
torch.Size([100, 100])
epoch:16,loss:950821.8750
torch.Size([100, 100])
epoch:17,loss:873213.0000
torch.Size([100, 100])
epoch:18,loss:806622.1250
torch.Size([100, 100])
epoch:19,loss:748877.8125
torch.

# 自定义传播函数 (重写前向函数与后向函数)

In [14]:
import torch
from torch.autograd import Variable
batch_n = 64#一个批次输入数据的数量
hidden_layer = 100
input_data = 1000#每个数据的特征为1000
output_data = 10
class Model(torch.nn.Module):#完成类继承的操作
    def __init__(self):
        super(Model,self).__init__()#类的初始化
        
    def forward(self,input,w1,w2):
        x = torch.mm(input,w1)  # h1
        x = torch.clamp(x,min = 0) # active function
        x = torch.mm(x,w2)      # output
        return x
    
    def backward(self):
        pass
model = Model()
x = Variable(torch.randn(batch_n,input_data),requires_grad=False)
y = Variable(torch.randn(batch_n,output_data),requires_grad=False)
#用Variable对Tensor数据类型变量进行封装的操作。requires_grad如果是F，表示该变量在进行自动梯度计算的过程中不会保留梯度值。
w1 = Variable(torch.randn(input_data,hidden_layer),requires_grad=True)
w2 = Variable(torch.randn(hidden_layer,output_data),requires_grad=True)

epoch_n=30

for epoch in range(epoch_n):
    y_pred = model(x,w1,w2)
    
    loss = (y_pred-y).pow(2).sum()
    print("epoch:{},loss:{:.4f}".format(epoch,loss.data))
    loss.backward()
    w1.data -= lr*w1.grad.data
    w2.data -= lr*w2.grad.data

    w1.grad.data.zero_()
    w2.grad.data.zero_()
    


epoch:0,loss:24798506.0000
epoch:1,loss:20088324.0000
epoch:2,loss:20575364.0000
epoch:3,loss:23572318.0000
epoch:4,loss:26630272.0000
epoch:5,loss:26788312.0000
epoch:6,loss:22561292.0000
epoch:7,loss:15488016.0000
epoch:8,loss:8979370.0000
epoch:9,loss:4733538.5000
epoch:10,loss:2508895.0000
epoch:11,loss:1440628.2500
epoch:12,loss:931967.4375
epoch:13,loss:674159.0000
epoch:14,loss:529030.7500
epoch:15,loss:436547.5000
epoch:16,loss:370912.5000
epoch:17,loss:320417.6562
epoch:18,loss:279588.2812
epoch:19,loss:245597.0312
epoch:20,loss:216811.5312
epoch:21,loss:192153.2969
epoch:22,loss:170882.7812
epoch:23,loss:152438.2969
epoch:24,loss:136357.0625
epoch:25,loss:122279.6328
epoch:26,loss:109923.2109
epoch:27,loss:99035.8828
epoch:28,loss:89414.2969
epoch:29,loss:80888.6641


# torch.nn.Sequential


In [5]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)   # 不保留梯度
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)  # 不保留梯度
models = torch.nn.Sequential(
    torch.nn.Linear(input_data, hidden_layer),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_layer, output_data)
)

# models = torch.nn.Sequential() 括号内是搭建的神经网络模型的结构, 
# 参数会按照定义好的序列传递
# 
# torch.nn.Linear() 做线性运算, 输入特征数, 输出特征数, 是否使用偏置, 默认为True
# 
# torch.nn.ReLU() 激活函数, 默认定义不需要参数
# 

# torch.nn.MSELoss

In [21]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.MSELoss()
x = Variable(torch.randn(100, 100))
y = Variable(torch.randn(100, 100))
loss = loss_f(x, y)
loss.data

tensor(2.0467)

# torch.nn.MSELoss()使用均方误差函数对损失值计算, 定义不需要传入参数, 使用实例时输入两个维度一样的参数

# torch.nn.L1Loss

In [25]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.L1Loss()
x = Variable(torch.randn(100, 100))
y = Variable(torch.randn(100, 100))
loss = loss_f(x, y)
loss.data

tensor(1.1216)

# torch.nn.MSELoss()使用平均绝对误差函数对损失值计算, 定义不需要传入参数, 使用实例时输入两个维度一样的参数

In [3]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.MSELoss()
x = Variable(torch.randn(100, 100))
y = Variable(torch.randn(100, 100))
loss = loss_f(x, y)


batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10


x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

models = torch.nn.Sequential(
    torch.nn.Linear(input_data, hidden_layer),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_layer, output_data)
)

epoch_n=12345
lr = 1e-6

# 模型训练
for epoch in range(epoch_n):
    y_pred = models(x)

    loss = loss_f(y_pred, y)
    if epoch%1000 == 0:
        print("epoch:{}, loss:{:.4f}".format(epoch, loss.data))
    models.zero_grad()

    loss.backward()

    for param in models.parameters():
        param.data -= param.grad.data*lr

epoch:0, loss:1.0648
epoch:1000, loss:1.0640
epoch:2000, loss:1.0631
epoch:3000, loss:1.0623
epoch:4000, loss:1.0614
epoch:5000, loss:1.0606
epoch:6000, loss:1.0598
epoch:7000, loss:1.0590
epoch:8000, loss:1.0581
epoch:9000, loss:1.0573
epoch:10000, loss:1.0565
epoch:11000, loss:1.0557
epoch:12000, loss:1.0548


# torch.optim

In [14]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.MSELoss()
x = Variable(torch.randn(100, 100))
y = Variable(torch.randn(100, 100))
loss = loss_f(x, y)


batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10


x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

models = torch.nn.Sequential(
    torch.nn.Linear(input_data, hidden_layer),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_layer, output_data)
)

epoch_n=123
lr = 1e-5
loss_f = torch.nn.MSELoss()

optimzer = torch.optim.Adam(models.parameters(), lr = lr)


# 模型训练
for epoch in range(epoch_n):
    y_pred = models(x)
    loss = loss_f(y_pred, y)
    print("Epoch:{}, Loss:{:.4f}".format(epoch, loss.data))
    optimzer.zero_grad()
    loss.backward()
    optimzer.step()

Epoch:0, Loss:0.9980
Epoch:1, Loss:0.9958
Epoch:2, Loss:0.9937
Epoch:3, Loss:0.9916
Epoch:4, Loss:0.9895
Epoch:5, Loss:0.9874
Epoch:6, Loss:0.9853
Epoch:7, Loss:0.9832
Epoch:8, Loss:0.9811
Epoch:9, Loss:0.9791
Epoch:10, Loss:0.9770
Epoch:11, Loss:0.9749
Epoch:12, Loss:0.9729
Epoch:13, Loss:0.9708
Epoch:14, Loss:0.9688
Epoch:15, Loss:0.9667
Epoch:16, Loss:0.9647
Epoch:17, Loss:0.9626
Epoch:18, Loss:0.9606
Epoch:19, Loss:0.9586
Epoch:20, Loss:0.9565
Epoch:21, Loss:0.9545
Epoch:22, Loss:0.9525
Epoch:23, Loss:0.9505
Epoch:24, Loss:0.9485
Epoch:25, Loss:0.9465
Epoch:26, Loss:0.9445
Epoch:27, Loss:0.9425
Epoch:28, Loss:0.9405
Epoch:29, Loss:0.9385
Epoch:30, Loss:0.9365
Epoch:31, Loss:0.9345
Epoch:32, Loss:0.9326
Epoch:33, Loss:0.9306
Epoch:34, Loss:0.9286
Epoch:35, Loss:0.9267
Epoch:36, Loss:0.9247
Epoch:37, Loss:0.9227
Epoch:38, Loss:0.9208
Epoch:39, Loss:0.9188
Epoch:40, Loss:0.9169
Epoch:41, Loss:0.9150
Epoch:42, Loss:0.9130
Epoch:43, Loss:0.9111
Epoch:44, Loss:0.9092
Epoch:45, Loss:0.907