In [42]:
pwd

'/Users/baijingyuan/jupyterPj/pytorch_practice'

In [43]:
import torch

In [44]:
torch.empty(3,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [45]:
x = torch.tensor([5.5, 3])

In [46]:
print(x)

tensor([5.5000, 3.0000])


In [47]:
x = torch.rand(5,3)

In [48]:
print(x)

tensor([[0.4874, 0.9415, 0.6074],
        [0.4554, 0.9872, 0.6349],
        [0.2027, 0.6128, 0.9628],
        [0.8822, 0.8551, 0.2986],
        [0.1383, 0.3929, 0.4397]])


In [49]:
result = torch.empty(5, 3)
x = torch.rand(5, 3)
y = torch.rand(5, 3)
result = torch.add(x, y)
print(x, y, result)

tensor([[0.2123, 0.1424, 0.1502],
        [0.7859, 0.5134, 0.7885],
        [0.4988, 0.0781, 0.9173],
        [0.7660, 0.1304, 0.4404],
        [0.2574, 0.6179, 0.4238]]) tensor([[0.4936, 0.9348, 0.8879],
        [0.9479, 0.5654, 0.1303],
        [0.6349, 0.1140, 0.6328],
        [0.3526, 0.0639, 0.7017],
        [0.9563, 0.2016, 0.5413]]) tensor([[0.7059, 1.0773, 1.0381],
        [1.7338, 1.0788, 0.9187],
        [1.1337, 0.1921, 1.5501],
        [1.1186, 0.1943, 1.1421],
        [1.2137, 0.8195, 0.9651]])


In [50]:
result.size()

torch.Size([5, 3])

In [51]:
y.size()

torch.Size([5, 3])

In [52]:
torch.Tensor([5, 3])
torch.tensor([5, 3])

tensor([5, 3])

In [53]:
y = torch.randn(5, 3) 
x = torch.rand(5, 3)

In [54]:
print(x)

tensor([[0.4559, 0.7120, 0.2219],
        [0.2581, 0.1372, 0.0854],
        [0.1462, 0.2865, 0.2870],
        [0.5127, 0.7986, 0.5871],
        [0.1493, 0.5187, 0.3689]])


In [55]:
print(y)

tensor([[-0.3891, -0.3139,  0.8295],
        [ 0.3435,  1.2583, -0.9577],
        [-0.1483,  0.9781, -1.8480],
        [-0.2281,  0.7332,  1.1610],
        [ 0.5940,  0.7403,  0.1029]])


In [56]:
import torch
x = torch.FloatTensor([5, 3])
y = torch.IntTensor([5.0, 3.0])

In [57]:
print(x)

tensor([5., 3.])


In [58]:
print(y)

tensor([5, 3], dtype=torch.int32)


In [59]:
a = torch.randn(5,3)

In [60]:
print(a)

tensor([[ 0.6032,  1.2109, -0.9783],
        [ 1.4730, -0.4425,  0.1360],
        [ 0.1464,  1.5923, -0.0047],
        [-1.7136,  0.8701, -1.9218],
        [-0.1205,  1.9350, -0.5295]])


randn   均值为0, 方差为1, float

In [62]:
import torch
x = torch.arange(0, 12).reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [63]:
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [64]:
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [65]:
x = torch.empty(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [66]:
a = torch.randn(2, 3)
a

tensor([[-0.8420, -0.5736, -0.3009],
        [-2.4455, -1.6021,  0.8904]])

In [67]:
b = torch.abs(a)
b

tensor([[0.8420, 0.5736, 0.3009],
        [2.4455, 1.6021, 0.8904]])

In [68]:
x = torch.rand(2, 3)
x

tensor([[0.1239, 0.5943, 0.9745],
        [0.4128, 0.6702, 0.9311]])

In [69]:
y = torch.rand(2, 3)
y

tensor([[0.2208, 0.4712, 0.8697],
        [0.4506, 0.2116, 0.1988]])

In [70]:
z = torch.add(x, y)
z

tensor([[0.3447, 1.0654, 1.8442],
        [0.8635, 0.8819, 1.1298]])

In [71]:
z = torch.add(x, 10)
z

tensor([[10.1239, 10.5943, 10.9745],
        [10.4128, 10.6702, 10.9311]])

In [72]:
a = torch.tensor([1, 2, 3, 4, 5, 6]).reshape(2, 3)
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [73]:
b = torch.clamp(a, 3, 3)

In [74]:
b

tensor([[3, 3, 3],
        [3, 3, 3]])

In [75]:
b = torch.clamp(a, 3, 4)

In [76]:
b

tensor([[3, 3, 3],
        [4, 4, 4]])

In [77]:
c = torch.div(a, b)
c

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.2500, 1.5000]])

In [78]:
import torch

In [79]:
a = torch.tensor([2, 3, 4])
a

tensor([2, 3, 4])

In [80]:
a = torch.pow(a, 2)
a

tensor([ 4,  9, 16])

In [81]:
a = torch.tensor([2, 3, 4])
a

tensor([2, 3, 4])

In [82]:
b = torch.pow(a, 2)

In [83]:
b

tensor([ 4,  9, 16])

In [84]:
a = torch.tensor([[1, 2, 3],[2, 3, 4]])
a

tensor([[1, 2, 3],
        [2, 3, 4]])

In [85]:
b = torch.tensor([[2, 3, 4],[1, 1, 1]])
b

tensor([[2, 3, 4],
        [1, 1, 1]])

In [86]:
c = torch.mm(a, b.T)

In [87]:
c

tensor([[20,  6],
        [29,  9]])

In [88]:
import torch
a = torch.randn(2, 3)
a

tensor([[-0.5711,  0.5093, -0.7649],
        [ 1.1576,  1.6526, -0.5625]])

In [89]:
b = torch.randn(3)
b

tensor([ 0.4192, -0.8984, -0.1498])

In [90]:
c = torch.mv(a, b)
c

tensor([-0.5824, -0.9151])

In [91]:
#这里用torch.nn实现一个MLP
from torch import nn

class MLP(nn.Module):
    def __init__(self, in_dim, hid_dim1, hid_dim2, out_dim):
        super(MLP, self).__init__()
        self.layer = nn.Sequential(
          nn.Linear(in_dim, hid_dim1),
          nn.ReLU(),
          nn.Linear(hid_dim1, hid_dim2),
          nn.ReLU(),
          nn.Linear(hid_dim2, out_dim),
          nn.ReLU()
       )
    def forward(self, x):
        x = self.layer(x)
        return x

# 简易神经网络

In [93]:
import torch
batch_n = 100#一个批次输入数据的数量
hidden_layer = 100
input_data = 1000#每个数据的特征为1000
output_data = 10

x = torch.randn(batch_n,input_data)
y = torch.randn(batch_n,output_data)


w1 = torch.randn(input_data,hidden_layer)
w2 = torch.randn(hidden_layer,output_data)

epoch_n = 20
lr = 1e-6


for epoch in range(epoch_n):
    h1=x.mm(w1)#(100,1000)*(1000,100)-->100*100
    print(h1.shape)
    h1=h1.clamp(min=0)
    y_pred = h1.mm(w2)
    
    loss = (y_pred-y).pow(2).sum()
    print("epoch:{},loss:{:.4f}".format(epoch,loss))
    
    grad_y_pred = 2*(y_pred-y)
    grad_w2 = h1.t().mm(grad_y_pred)
    
    grad_h = grad_y_pred.clone()
    grad_h = grad_h.mm(w2.t())
    grad_h.clamp_(min=0)#将小于0的值全部赋值为0，相当于sigmoid
    grad_w1 = x.t().mm(grad_h)
    
    w1 = w1 -lr*grad_w1
    w2 = w2 -lr*grad_w2


torch.Size([100, 100])
epoch:0,loss:51473864.0000
torch.Size([100, 100])
epoch:1,loss:112936728.0000
torch.Size([100, 100])
epoch:2,loss:441915904.0000
torch.Size([100, 100])
epoch:3,loss:831945088.0000
torch.Size([100, 100])
epoch:4,loss:51561628.0000
torch.Size([100, 100])
epoch:5,loss:20461974.0000
torch.Size([100, 100])
epoch:6,loss:11566545.0000
torch.Size([100, 100])
epoch:7,loss:7435552.5000
torch.Size([100, 100])
epoch:8,loss:5144543.0000
torch.Size([100, 100])
epoch:9,loss:3745824.5000
torch.Size([100, 100])
epoch:10,loss:2840056.2500
torch.Size([100, 100])
epoch:11,loss:2228726.0000
torch.Size([100, 100])
epoch:12,loss:1803439.5000
torch.Size([100, 100])
epoch:13,loss:1499883.0000
torch.Size([100, 100])
epoch:14,loss:1278300.5000
torch.Size([100, 100])
epoch:15,loss:1113128.0000
torch.Size([100, 100])
epoch:16,loss:987286.0625
torch.Size([100, 100])
epoch:17,loss:889374.5625
torch.Size([100, 100])
epoch:18,loss:811546.1250
torch.Size([100, 100])
epoch:19,loss:748356.3125


# 输入层 (X，100*1000维特征)
    |
    | 线性变换 (权重 W1 1000*100层)
    v
# 隐藏层线性输出 (H1_linear 100*100)
    |
    | 激活函数 (ReLU min=0)
    v
# 隐藏层激活输出 (H1  100*100)
    |
    | 线性变换 (权重 W2 100*10)
    v
# 输出层预测值 (Y_pred 100*10)
    |
    | 损失函数 (如均方误差  sigma(y_pred - y))
    v
# 损失值 (Loss)

#
#
#


# 损失值 (Loss)
    ^
    | 计算损失对预测输出 Y_pred 的梯度
    |
# 输出层预测值 (Y_pred)
    ^
    | 计算损失对 W2 和 H1 的梯度
    |
# 隐藏层激活输出 (H1)
    ^
    | 计算激活函数 (ReLU) 的梯度
    |
# 隐藏层线性输出 (H1_linear)
    ^
    | 计算损失对 W1 的梯度
    |
# 输入层 (X)


In [96]:
import torch
a = torch.randn(2, 3)
a

tensor([[-0.7912, -0.7973, -0.9928],
        [ 1.9184,  1.7247,  0.0890]])

In [97]:
b = torch.randn(2, 3)
b

tensor([[ 0.6542,  1.5756,  1.2641],
        [-0.9960, -0.2708, -1.0823]])

In [98]:
c = torch.div(a, b)
c

tensor([[-1.2094, -0.5060, -0.7854],
        [-1.9261, -6.3698, -0.0822]])

# 完整神经网络

In [100]:
import torch
from torch.autograd import Variable
batch_n = 100#一个批次输入数据的数量
hidden_layer = 100
input_data = 1000#每个数据的特征为1000
output_data = 10

x = Variable(torch.randn(batch_n,input_data),requires_grad=False)
y = Variable(torch.randn(batch_n,output_data),requires_grad=False)
#用Variable对Tensor数据类型变量进行封装的操作。requires_grad如果是False，表示该变量在进行自动梯度计算的过程中不会保留梯度值。
w1 = Variable(torch.randn(input_data,hidden_layer),requires_grad=True)
w2 = Variable(torch.randn(hidden_layer,output_data),requires_grad=True)

#学习率和迭代次数
epoch_n=50
lr=1e-6

for epoch in range(epoch_n):
    h1=x.mm(w1)#(100,1000)*(1000,100)-->100*100
    print(h1.shape)
    h1=h1.clamp(min=0)
    y_pred = h1.mm(w2)
    #y_pred = x.mm(w1).clamp(min=0).mm(w2)
    loss = (y_pred-y).pow(2).sum()
    print("epoch:{},loss:{:.4f}".format(epoch,loss.data))
    
#     grad_y_pred = 2*(y_pred-y)
#     grad_w2 = h1.t().mm(grad_y_pred)
    loss.backward()#后向传播
#     grad_h = grad_y_pred.clone()
#     grad_h = grad_h.mm(w2.t())
#     grad_h.clamp_(min=0)#将小于0的值全部赋值为0，相当于sigmoid
#     grad_w1 = x.t().mm(grad_h)
    w1.data -= lr*w1.grad.data
    w2.data -= lr*w2.grad.data

    w1.grad.data.zero_()
    w2.grad.data.zero_()
    
#     w1 = w1 -lr*grad_w1
#     w2 = w2 -lr*grad_w2


torch.Size([100, 100])
epoch:0,loss:39410624.0000
torch.Size([100, 100])
epoch:1,loss:50610140.0000
torch.Size([100, 100])
epoch:2,loss:190803104.0000
torch.Size([100, 100])
epoch:3,loss:725850880.0000
torch.Size([100, 100])
epoch:4,loss:487000256.0000
torch.Size([100, 100])
epoch:5,loss:6520564.0000
torch.Size([100, 100])
epoch:6,loss:4930673.5000
torch.Size([100, 100])
epoch:7,loss:3880887.0000
torch.Size([100, 100])
epoch:8,loss:3144816.0000
torch.Size([100, 100])
epoch:9,loss:2606876.2500
torch.Size([100, 100])
epoch:10,loss:2200566.5000
torch.Size([100, 100])
epoch:11,loss:1885770.6250
torch.Size([100, 100])
epoch:12,loss:1636482.7500
torch.Size([100, 100])
epoch:13,loss:1435995.6250
torch.Size([100, 100])
epoch:14,loss:1272471.1250
torch.Size([100, 100])
epoch:15,loss:1137558.2500
torch.Size([100, 100])
epoch:16,loss:1024735.8750
torch.Size([100, 100])
epoch:17,loss:929558.6250
torch.Size([100, 100])
epoch:18,loss:848454.7500
torch.Size([100, 100])
epoch:19,loss:778858.7500
torch

# 自定义传播函数 (重写前向函数与后向函数)

In [102]:
import torch
from torch.autograd import Variable
batch_n = 64#一个批次输入数据的数量
hidden_layer = 100
input_data = 1000#每个数据的特征为1000
output_data = 10
class Model(torch.nn.Module):#完成类继承的操作
    def __init__(self):
        super(Model,self).__init__()#类的初始化
        
    def forward(self,input,w1,w2):
        x = torch.mm(input,w1)  # h1
        x = torch.clamp(x,min = 0) # active function
        x = torch.mm(x,w2)      # output
        return x
    
    def backward(self):
        pass
model = Model()
x = Variable(torch.randn(batch_n,input_data),requires_grad=False)
y = Variable(torch.randn(batch_n,output_data),requires_grad=False)
#用Variable对Tensor数据类型变量进行封装的操作。requires_grad如果是F，表示该变量在进行自动梯度计算的过程中不会保留梯度值。
w1 = Variable(torch.randn(input_data,hidden_layer),requires_grad=True)
w2 = Variable(torch.randn(hidden_layer,output_data),requires_grad=True)

epoch_n=30

for epoch in range(epoch_n):
    y_pred = model(x,w1,w2)
    
    loss = (y_pred-y).pow(2).sum()
    print("epoch:{},loss:{:.4f}".format(epoch,loss.data))
    loss.backward()
    w1.data -= lr*w1.grad.data
    w2.data -= lr*w2.grad.data

    w1.grad.data.zero_()
    w2.grad.data.zero_()
    


epoch:0,loss:35758028.0000
epoch:1,loss:39210404.0000
epoch:2,loss:46610216.0000
epoch:3,loss:47317268.0000
epoch:4,loss:35344444.0000
epoch:5,loss:18168670.0000
epoch:6,loss:7505094.5000
epoch:7,loss:3350727.0000
epoch:8,loss:1971500.5000
epoch:9,loss:1436996.7500
epoch:10,loss:1156504.5000
epoch:11,loss:967096.6250
epoch:12,loss:821854.1250
epoch:13,loss:704703.7500
epoch:14,loss:608131.7500
epoch:15,loss:527575.0625
epoch:16,loss:459903.4688
epoch:17,loss:402616.8750
epoch:18,loss:353769.6250
epoch:19,loss:312068.5000
epoch:20,loss:276184.8438
epoch:21,loss:245141.6562
epoch:22,loss:218210.7500
epoch:23,loss:194745.2031
epoch:24,loss:174233.6250
epoch:25,loss:156243.5156
epoch:26,loss:140416.3906
epoch:27,loss:126449.9141
epoch:28,loss:114104.5703
epoch:29,loss:103143.5781


# torch.nn.Sequential


In [104]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)   # 不保留梯度
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)  # 不保留梯度
models = torch.nn.Sequential(
    torch.nn.Linear(input_data, hidden_layer),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_layer, output_data)
)

# models = torch.nn.Sequential() 括号内是搭建的神经网络模型的结构, 
# 参数会按照定义好的序列传递
# 
# torch.nn.Linear() 做线性运算, 输入特征数, 输出特征数, 是否使用偏置, 默认为True
# 
# torch.nn.ReLU() 激活函数, 默认定义不需要参数
# 

# torch.nn.MSELoss

In [107]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.MSELoss()
x = Variable(torch.randn(100, 100))
y = Variable(torch.randn(100, 100))
loss = loss_f(x, y)
loss.data

tensor(2.0406)

# torch.nn.MSELoss()使用均方误差函数对损失值计算, 定义不需要传入参数, 使用实例时输入两个维度一样的参数

# torch.nn.L1Loss

In [110]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.L1Loss()
x = Variable(torch.randn(100, 100))
y = Variable(torch.randn(100, 100))
loss = loss_f(x, y)
loss.data

tensor(1.1345)

# torch.nn.MSELoss()使用平均绝对误差函数对损失值计算, 定义不需要传入参数, 使用实例时输入两个维度一样的参数

In [112]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.MSELoss()
x = Variable(torch.randn(100, 100))
y = Variable(torch.randn(100, 100))
loss = loss_f(x, y)


batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10


x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

models = torch.nn.Sequential(
    torch.nn.Linear(input_data, hidden_layer),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_layer, output_data)
)

epoch_n=12345
lr = 1e-6

# 模型训练
for epoch in range(epoch_n):
    y_pred = models(x)

    loss = loss_f(y_pred, y)
    if epoch%1000 == 0:
        print("epoch:{}, loss:{:.4f}".format(epoch, loss.data))
    models.zero_grad()

    loss.backward()

    for param in models.parameters():
        param.data -= param.grad.data*lr

epoch:0, loss:1.0164
epoch:1000, loss:1.0156
epoch:2000, loss:1.0148
epoch:3000, loss:1.0140
epoch:4000, loss:1.0132
epoch:5000, loss:1.0124
epoch:6000, loss:1.0116
epoch:7000, loss:1.0108
epoch:8000, loss:1.0100
epoch:9000, loss:1.0092
epoch:10000, loss:1.0084
epoch:11000, loss:1.0077
epoch:12000, loss:1.0069


# torch.optim

In [114]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.MSELoss()
x = Variable(torch.randn(100, 100))
y = Variable(torch.randn(100, 100))
loss = loss_f(x, y)


batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10


x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

models = torch.nn.Sequential(
    torch.nn.Linear(input_data, hidden_layer),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_layer, output_data)
)

epoch_n=123
lr = 1e-5
loss_f = torch.nn.MSELoss()

optimzer = torch.optim.Adam(models.parameters(), lr = lr)


# 模型训练
for epoch in range(epoch_n):
    y_pred = models(x)
    loss = loss_f(y_pred, y)
    print("Epoch:{}, Loss:{:.4f}".format(epoch, loss.data))
    optimzer.zero_grad()
    loss.backward()
    optimzer.step()

Epoch:0, Loss:1.1271
Epoch:1, Loss:1.1249
Epoch:2, Loss:1.1227
Epoch:3, Loss:1.1205
Epoch:4, Loss:1.1183
Epoch:5, Loss:1.1161
Epoch:6, Loss:1.1139
Epoch:7, Loss:1.1117
Epoch:8, Loss:1.1095
Epoch:9, Loss:1.1073
Epoch:10, Loss:1.1052
Epoch:11, Loss:1.1030
Epoch:12, Loss:1.1008
Epoch:13, Loss:1.0987
Epoch:14, Loss:1.0965
Epoch:15, Loss:1.0944
Epoch:16, Loss:1.0922
Epoch:17, Loss:1.0901
Epoch:18, Loss:1.0880
Epoch:19, Loss:1.0858
Epoch:20, Loss:1.0837
Epoch:21, Loss:1.0816
Epoch:22, Loss:1.0795
Epoch:23, Loss:1.0774
Epoch:24, Loss:1.0753
Epoch:25, Loss:1.0732
Epoch:26, Loss:1.0711
Epoch:27, Loss:1.0690
Epoch:28, Loss:1.0669
Epoch:29, Loss:1.0649
Epoch:30, Loss:1.0628
Epoch:31, Loss:1.0607
Epoch:32, Loss:1.0587
Epoch:33, Loss:1.0566
Epoch:34, Loss:1.0546
Epoch:35, Loss:1.0525
Epoch:36, Loss:1.0505
Epoch:37, Loss:1.0485
Epoch:38, Loss:1.0464
Epoch:39, Loss:1.0444
Epoch:40, Loss:1.0424
Epoch:41, Loss:1.0404
Epoch:42, Loss:1.0384
Epoch:43, Loss:1.0364
Epoch:44, Loss:1.0344
Epoch:45, Loss:1.032

# 搭建神经网络实现手写数据集

In [116]:
import torch
import torchvision
from torchvision import datasets, transforms

transform = transforms.Compose([
     transforms.ToTensor(),
     transforms.Lambda(lambda x: x.repeat(3,1,1)),
     transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
 ])   
data_train = datasets.MNIST(root = "./data/",
                           transform = transform,
                           train = True,
                           download = True)

data_test = datasets.MNIST(root = "./data/",
                           transform = transform,
                           train = False)

# torch.transforms
torch.transforms中有大量数据变换类，如：

# torchvision.transforms.Resize
用于对载入的图片数据按照我们需求的大小进行缩放。传递的参数可以是一个整型数据，也可以是一个类似于(h,w)的序列。h代表高度，w代表宽度，如果输入的是整型数据那么h和w都等于这个数。

# torchvision.transforms.Scale
用于对载入的图片数据按照我们需求的大小进行缩放。和Resize类似。

# torchvision.transforms.CenterCrop
用于对载入的图片以图片中心为参考点，按照我们需要的大小进行裁剪。传递给这个类的参数可以是一个整型数据，也可以是一个类似于(h,w)的序列。

# torchvision.transforms.RandomCrop
用于对载入的图片按照我们需要的大小进行随机裁剪。传递给这个类的参数可以是一个整型数据，也可以是一个类似于(h,w)的序列。

# torchvision.transforms.RandomHorizontalFlip
用于对载入的图片按随机概率进行水平翻转。我们通过传递给这个类的自定义随机概率，如果没有定义，则使用默认的概率为0.5

# torchvision.transforms.RandomVerticalFlip
用于对载入的图片按随机概率进行垂直翻转。我们通过传递给这个类的自定义随机概率，如果没有定义，则使用默认的概率为0.5

# torchvision.transforms.ToTensor
用于对载入的图片数据进行类型转换，将之前构成PIL图片数据转换为Tensor数据类型的变量，让PyTorch能够对其进行计算和处理。

# torchvision.transforms.ToPILImage:
用于对Tensor变量的数据转换成PIL图片数据，主要为方便图片显示。
543

In [183]:
#torchvision.transforms: 
transform=transforms.Compose(
    [transforms.ToTensor(),#将PILImage转换为张量
     transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))#将[0, 1]归一化到[-1, 1]
     #前面的（0.5，0.5，0.5） 是 R G B 三个通道上的均值， 后面(0.5, 0.5, 0.5)是三个通道的标准差
    ])
#上述代码我们可以将transforms.Compose()看作一种容器，它能够同时对多种数据变换进行组合。
#传入的参数是一个列表，列表中的元素就是对载入数据进行的变换操作。


In [ ]:
import torch 
import torchvision
from torchvision import datasets,transforms
from torch.autograd import Variable
import numpy as np
import matplotlib.pyplot as plt

#torchvision.transforms: 常用的图片变换，例如裁剪、旋转等；
# transform=transforms.Compose(
#     [transforms.ToTensor(),#将PILImage转换为张量
#      transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))#将[0, 1]归一化到[-1, 1]
#      #前面的（0.5，0.5，0.5） 是 R G B 三个通道上的均值， 后面(0.5, 0.5, 0.5)是三个通道的标准差
#     ])
transform = transforms.Compose([
     transforms.ToTensor(),
     transforms.Lambda(lambda x: x.repeat(3,1,1)),
     transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
 ])   # 修改的位置

data_train = datasets.MNIST(root="./data/",
                           transform=transform,
                           train = True,
                           download = True)
data_test = datasets.MNIST(root="./data/",
                          transform = transform,
                          train = False)

data_loader_train=torch.utils.data.DataLoader(dataset=data_train,
                                       batch_size=64,#每个batch载入的图片数量，默认为1,这里设置为64
                                        shuffle=True,
                                        #num_workers=2#载入训练数据所需的子任务数
                                       )
data_loader_test=torch.utils.data.DataLoader(dataset=data_test,
                                      batch_size=64,
                                      shuffle=True)
                                      #num_workers=2)

#预览
#在尝试过多次之后，发现错误并不是这一句引发的，而是因为图片格式是灰度图只有一个channel，需要变成RGB图才可以，所以将其中一行做了修改：
images,labels = next(iter(data_loader_train))
# dataiter = iter(data_loader_train) #随机从训练数据中取一些数据
# images, labels = dataiter.next()

img = torchvision.utils.make_grid(images)

img = img.numpy().transpose(1,2,0)
std = [0.5,0.5,0.5]
mean = [0.5,0.5,0.5]
img = img*std+mean
print([labels[i] for i in range(64)])
plt.imshow(img)

import math
import torch
import torch.nn as nn
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        
        #构建卷积层之后的全连接层以及分类器
        self.conv1 = nn.Sequential(
                nn.Conv2d(3,64,kernel_size=3,stride=1,padding=1),
                nn.ReLU(),
                nn.Conv2d(64,128,kernel_size=3,stride=1,padding=1),
                nn.ReLU(),
                nn.MaxPool2d(stride=2,kernel_size=2)
                )
        
        self.dense = torch.nn.Sequential(
                nn.Linear(14*14*128,1024),
                nn.ReLU(),
                nn.Dropout(p=0.5),
                nn.Linear(1024,10)
            )
        
    def forward(self,x):
        x=self.conv1(x)
        x=x.view(-1,14*14*128)
        x=self.dense(x)
        return x

model = Model()
cost = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters())
print(model)

n_epochs = 5

for epoch in range(n_epochs):
    running_loss = 0.0
    running_correct = 0
    print("Epoch {}/{}".format(epoch,n_epochs))
    print("-"*10)
    for data in data_loader_train:
        X_train,y_train = data
        X_train,y_train = Variable(X_train),Variable(y_train)
        outputs = model(X_train)
        _,pred=torch.max(outputs.data,1)
        optimizer.zero_grad()
        loss = cost(outputs,y_train)
        
        loss.backward()
        optimizer.step()
        running_loss += loss.data
        running_correct += torch.sum(pred == y_train.data)
    testing_correct = 0
    for data in data_loader_test:
        X_test,y_test = data
        X_test,y_test = Variable(X_test),Variable(y_test)
        outputs = model(X_test)
        _,pred=torch.max(outputs.data,1)
        testing_correct += torch.sum(pred == y_test.data)
    print("Loss is:{:4f},Train Accuracy is:{:.4f}%,Test Accuracy is:{:.4f}".format(running_loss/len(data_train),100*running_correct/len(data_train)
                                                                                  ,100*testing_correct/len(data_test)))

data_loader_test = torch.utils.data.DataLoader(dataset=data_test,
                                              batch_size = 4,
                                              shuffle = True)
X_test,y_test = next(iter(data_loader_test))
inputs = Variable(X_test)
pred = model(inputs)
_,pred = torch.max(pred,1)

print("Predict Label is:",[i for i in pred.data])
print("Real Label is:",[i for i in y_test])
img = torchvision.utils.make_grid(X_test)
img = img.numpy().transpose(1,2,0)

std = [0.5,0.5,0.5]
mean = [0.5,0.5,0.5]
img = img*std+mean
plt.imshow(img)

