In [26]:
pwd

'/Users/baijingyuan/jupyterPj/pytorch_practice'

import torch

In [16]:
torch.empty(3,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [18]:
x = torch.tensor([5.5, 3])

In [20]:
print(x)

tensor([5.5000, 3.0000])


In [22]:
x = torch.rand(5,3)

In [24]:
print(x)

tensor([[0.3022, 0.9977, 0.3151],
        [0.3147, 0.3222, 0.7463],
        [0.1571, 0.3295, 0.3977],
        [0.6116, 0.7345, 0.9638],
        [0.1245, 0.7521, 0.3267]])


In [61]:
result = torch.empty(5, 3)
x = torch.rand(5, 3)
y = torch.rand(5, 3)
result = torch.add(x, y)
print(x, y, result)

tensor([[0.7988, 0.4484, 0.4187],
        [0.4488, 0.2201, 0.7110],
        [0.1796, 0.9812, 0.5387],
        [0.5059, 0.1817, 0.4603],
        [0.5799, 0.3885, 0.6683]]) tensor([[0.9356, 0.7896, 0.9591],
        [0.5162, 0.5644, 0.1231],
        [0.3896, 0.6357, 0.9558],
        [0.6159, 0.1719, 0.3662],
        [0.7664, 0.5161, 0.4988]]) tensor([[1.7344, 1.2380, 1.3778],
        [0.9650, 0.7845, 0.8340],
        [0.5691, 1.6169, 1.4945],
        [1.1217, 0.3536, 0.8265],
        [1.3463, 0.9046, 1.1671]])


In [62]:
result.size()

torch.Size([5, 3])

In [63]:
y.size()

torch.Size([5, 3])

In [75]:
torch.Tensor([5, 3])
torch.tensor([5, 3])

tensor([5, 3])

In [81]:
y = torch.randn(5, 3) 
x = torch.rand(5, 3)

In [83]:
print(x)

tensor([[0.8220, 0.0360, 0.8679],
        [0.5416, 0.7822, 0.0012],
        [0.0966, 0.8848, 0.9145],
        [0.9756, 0.1376, 0.3397],
        [0.3591, 0.2048, 0.8002]])


In [85]:
print(y)

tensor([[-0.5581, -0.1057,  0.4288],
        [ 0.9190,  1.6343,  0.0696],
        [ 1.2717,  0.9356, -1.0167],
        [-0.4650,  0.4329,  0.7812],
        [ 0.9244, -0.9421, -0.0802]])


In [6]:
import torch
x = torch.FloatTensor([5, 3])
y = torch.IntTensor([5.0, 3.0])

In [9]:
print(x)

tensor([5., 3.])


In [11]:
print(y)

tensor([5, 3], dtype=torch.int32)


In [13]:
a = torch.randn(5,3)

In [15]:
print(a)

tensor([[ 0.9500, -1.4548, -1.9308],
        [ 0.0068, -0.6253, -0.2284],
        [ 0.8488, -0.3014, -1.3392],
        [-1.1099,  0.3267,  1.3600],
        [-0.5708,  2.1047,  0.5551]])


randn   均值为0, 方差为1, float

In [18]:
import torch
x = torch.arange(0, 12).reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [20]:
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [24]:
x = torch.empty(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
a = torch.randn(2, 3)
a

tensor([[-0.0570, -0.6950,  0.7398],
        [-0.2683,  0.0319, -0.6639]])

In [30]:
b = torch.abs(a)
b

tensor([[0.0570, 0.6950, 0.7398],
        [0.2683, 0.0319, 0.6639]])

In [34]:
x = torch.rand(2, 3)
x

tensor([[0.4057, 0.0684, 0.0440],
        [0.0549, 0.5517, 0.3807]])

In [36]:
y = torch.rand(2, 3)
y

tensor([[0.9987, 0.7820, 0.4576],
        [0.3514, 0.1293, 0.0601]])

In [38]:
z = torch.add(x, y)
z

tensor([[1.4044, 0.8504, 0.5017],
        [0.4062, 0.6810, 0.4408]])

In [40]:
z = torch.add(x, 10)
z

tensor([[10.4057, 10.0684, 10.0440],
        [10.0549, 10.5517, 10.3807]])

In [42]:
a = torch.tensor([1, 2, 3, 4, 5, 6]).reshape(2, 3)
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [44]:
b = torch.clamp(a, 3, 3)

In [46]:
b

tensor([[3, 3, 3],
        [3, 3, 3]])

In [48]:
b = torch.clamp(a, 3, 4)

In [50]:
b

tensor([[3, 3, 3],
        [4, 4, 4]])

In [52]:
c = torch.div(a, b)
c

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.2500, 1.5000]])

In [2]:
import torch

In [4]:
a = torch.tensor([2, 3, 4])
a

tensor([2, 3, 4])

In [8]:
a = torch.pow(a, 2)
a

tensor([ 16,  81, 256])

In [10]:
a = torch.tensor([2, 3, 4])
a

tensor([2, 3, 4])

In [12]:
b = torch.pow(a, 2)

In [14]:
b

tensor([ 4,  9, 16])

In [18]:
a = torch.tensor([[1, 2, 3],[2, 3, 4]])
a

tensor([[1, 2, 3],
        [2, 3, 4]])

In [20]:
b = torch.tensor([[2, 3, 4],[1, 1, 1]])
b

tensor([[2, 3, 4],
        [1, 1, 1]])

In [22]:
c = torch.mm(a, b.T)

In [24]:
c

tensor([[20,  6],
        [29,  9]])

In [6]:
import torch
a = torch.randn(2, 3)
a

tensor([[-0.0929, -0.0762, -1.5224],
        [ 1.0897,  0.0570,  1.7094]])

In [8]:
b = torch.randn(3)
b

tensor([ 1.6427, -1.1543, -1.3970])

In [10]:
c = torch.mv(a, b)
c

tensor([ 2.0622, -0.6639])

In [5]:
#这里用torch.nn实现一个MLP
from torch import nn

class MLP(nn.Module):
    def __init__(self, in_dim, hid_dim1, hid_dim2, out_dim):
        super(MLP, self).__init__()
        self.layer = nn.Sequential(
          nn.Linear(in_dim, hid_dim1),
          nn.ReLU(),
          nn.Linear(hid_dim1, hid_dim2),
          nn.ReLU(),
          nn.Linear(hid_dim2, out_dim),
          nn.ReLU()
       )
    def forward(self, x):
        x = self.layer(x)
        return x

In [ ]:
import torch
batch_n = 100#一个批次输入数据的数量
hidden_layer = 100
input_data = 1000#每个数据的特征为1000
output_data = 10

x = torch.randn(batch_n,input_data)
y = torch.randn(batch_n,output_data)


w1 = torch.randn(input_data,hidden_layer)
w2 = torch.randn(hidden_layer,output_data)

epoch_n = 20
lr = 1e-6


for epoch in range(epoch_n):
    h1=x.mm(w1)#(100,1000)*(1000,100)-->100*100
    print(h1.shape)
    h1=h1.clamp(min=0)
    y_pred = h1.mm(w2)
    
    loss = (y_pred-y).pow(2).sum()
    print("epoch:{},loss:{:.4f}".format(epoch,loss))
    
    grad_y_pred = 2*(y_pred-y)
    grad_w2 = h1.t().mm(grad_y_pred)
    
    grad_h = grad_y_pred.clone()
    grad_h = grad_h.mm(w2.t())
    grad_h.clamp_(min=0)#将小于0的值全部赋值为0，相当于sigmoid
    grad_w1 = x.t().mm(grad_h)
    
    w1 = w1 -lr*grad_w1
    w2 = w2 -lr*grad_w2


# 输入层 (X，1000维特征)
    |
    | 线性变换 (权重 W1)
    v
# 隐藏层线性输出 (H1_linear)
    |
    | 激活函数 (ReLU)
    v
# 隐藏层激活输出 (H1)
    |
    | 线性变换 (权重 W2)
    v
# 输出层预测值 (Y_pred)
    |
    | 损失函数 (如均方误差)
    v
# 损失值 (Loss)

#
#
#


# 损失值 (Loss)
    ^
    | 计算损失对预测输出 Y_pred 的梯度
    |
# 输出层预测值 (Y_pred)
    ^
    | 计算损失对 W2 和 H1 的梯度
    |
# 隐藏层激活输出 (H1)
    ^
    | 计算激活函数 (ReLU) 的梯度
    |
# 隐藏层线性输出 (H1_linear)
    ^
    | 计算损失对 W1 的梯度
    |
# 输入层 (X)
